version: "3.7"
services:
  app:
    build: rails-test
    command: bash -c "bundle install && bundle exec rails db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails_test
    container_name: rails_test
    ports:
      - 3000:3000
    volumes:
      - ./rails-test:/railsTest
