#!/bin/bash

if [ ! -d rails-test ]; then
    git clone --branch rails-7.0.3 https://github.com/mo-nathan/rails-test.git
    echo Cloned mo-nathan/rails-test
else
    echo rails-test directory exists
fi

docker-compose build
docker-compose up -d
